export function defaultRootPath(domain: string): string {
  return `/var/www/${domain}/public_html`;
}

export function renderConfig(domain: string, rootPath?: string): string {
  const root = rootPath ?? defaultRootPath(domain);
  return `# Generated by rinpanel for ${domain}
server {
    listen 80;
    server_name ${domain};
    root ${root};
    index index.html;

    # Hide nginx version from response headers and error pages.
    server_tokens off;

    # Security response headers ('always' so error responses get them too).
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=(), payment=()" always;
    # Uncomment + tune once your site is CSP-ready:
    # add_header Content-Security-Policy "default-src 'self'" always;

    # Cap request body size (raise if you accept larger uploads).
    client_max_body_size 10m;

    # Custom themed error pages.
    error_page 404 /_rinpanel/404.html;
    error_page 502 503 504 /_rinpanel/502.html;
    location ^~ /_rinpanel/ {
        internal;
        root ${root};
    }

    # Block dotfiles (.git, .env, .htaccess, .ssh, ...).
    location ~ /\\. {
        deny all;
        access_log off;
        log_not_found off;
        return 404;
    }

    # Block common sensitive file extensions.
    location ~* \\.(env|log|sql|sqlite|db|bak|backup|swp|swo)$ {
        deny all;
        access_log off;
        log_not_found off;
        return 404;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    access_log /var/log/nginx/${domain}.access.log;
    error_log /var/log/nginx/${domain}.error.log;
}
`;
}

interface PageOpts {
  title: string;
  eyebrow: string;
  heading: string;
  body: string;
  accent?: string;
}

function pageHtml({ title, eyebrow, heading, body, accent = "#84cc16" }: PageOpts): string {
  // Escape any HTML special chars in dynamic strings (defense in depth — these
  // come from validated domains so should be safe, but we belt-and-suspenders).
  const esc = (s: string) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  const T = esc(title);
  const E = esc(eyebrow);
  const H = esc(heading);
  const B = esc(body);
  return `<!doctype html>
<html lang="id">
<head>
<meta charset="utf-8" />
<title>${T}</title>
<meta name="viewport" content="width=device-width,initial-scale=1" />
<meta name="robots" content="noindex,nofollow" />
<style>
  :root { color-scheme: dark; --accent: ${accent}; }
  * { box-sizing: border-box; }
  body {
    margin: 0; min-height: 100vh; padding: 1.5rem;
    display: grid; place-items: center;
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    background:
      radial-gradient(130% 100% at 50% -8%, color-mix(in oklch, var(--accent) 12%, transparent) 0%, transparent 46%),
      #0a0a0a;
    color: #e4e4e7;
  }
  .card {
    position: relative;
    width: 100%; max-width: 32rem;
    padding: 2.25rem 2.5rem 1.5rem;
    border: 1px solid rgba(255,255,255,0.09);
    border-radius: 0.75rem;
    background: rgba(20,22,26,0.7);
    backdrop-filter: blur(16px) saturate(1.35);
    -webkit-backdrop-filter: blur(16px) saturate(1.35);
    box-shadow: 0 24px 60px -30px rgba(0,0,0,0.85);
  }
  .card::before, .card::after {
    content: ""; position: absolute; width: 12px; height: 12px;
    border-color: color-mix(in oklch, var(--accent) 55%, transparent);
    pointer-events: none;
  }
  .card::before { top: 10px; left: 10px; border-top: 1px solid; border-left: 1px solid; }
  .card::after  { bottom: 10px; right: 10px; border-bottom: 1px solid; border-right: 1px solid; }
  .eyebrow {
    color: color-mix(in oklch, var(--accent) 80%, white 20%);
    font-size: 0.6rem; letter-spacing: 0.22em; text-transform: uppercase;
    margin: 0;
  }
  .heading {
    font-size: 1.75rem; font-weight: 700; margin: 0.7rem 0 0 0;
    color: #fff; line-height: 1.15; letter-spacing: 0.01em; word-break: break-word;
    text-shadow:
      0 0 18px color-mix(in oklch, var(--accent) 55%, transparent),
      0 0 4px color-mix(in oklch, var(--accent) 40%, transparent);
  }
  .body { margin: 0.9rem 0 0 0; color: #a1a1aa; font-size: 0.85rem; line-height: 1.55; }
  .footer {
    display: flex; justify-content: space-between; align-items: center;
    margin-top: 1.5rem; padding-top: 0.9rem;
    border-top: 1px solid rgba(255,255,255,0.06);
  }
  .footer span { color: #52525b; font-size: 0.55rem; letter-spacing: 0.22em; text-transform: uppercase; }
</style>
</head>
<body>
  <div class="card">
    <p class="eyebrow">${E}</p>
    <h1 class="heading">${H}</h1>
    <p class="body">${B}</p>
    <div class="footer">
      <span>rinpanel</span>
      <span>console</span>
    </div>
  </div>
</body>
</html>
`;
}

export function renderPlaceholderHtml(domain: string): string {
  return pageHtml({
    title: `${domain} · siap`,
    eyebrow: "domain · siap",
    heading: domain,
    body: "Domain ini sudah aktif dan siap digunakan. Silakan unggah berkas situs Anda melalui panel kontrol untuk menampilkan konten.",
  });
}

export function renderError404Html(): string {
  return pageHtml({
    title: "404 · Tidak Ditemukan",
    eyebrow: "404 · tidak ditemukan",
    heading: "Halaman tidak ditemukan",
    body: "Halaman yang Anda cari tidak tersedia. Silakan periksa kembali alamat yang Anda masukkan.",
  });
}

export function renderError502Html(): string {
  return pageHtml({
    title: "502 · Layanan Tidak Tersedia",
    eyebrow: "502 · layanan tidak tersedia",
    heading: "Layanan sedang tidak dapat dijangkau",
    body: "Server sedang tidak dapat melayani permintaan saat ini. Silakan coba kembali beberapa saat lagi.",
    accent: "#f59e0b",
  });
}

export function renderUnboundHtml(): string {
  return pageHtml({
    title: "Domain belum terdaftar",
    eyebrow: "domain · belum terdaftar",
    heading: "Domain belum terdaftar",
    body: "Domain ini belum terdaftar pada sistem. Jika Anda adalah pemilik server, silakan tambahkan domain melalui panel kontrol.",
    accent: "#a1a1aa",
  });
}
