import { describe, it, expect } from "vitest";
import {
  renderConfig,
  renderError404Html,
  renderError502Html,
  renderPlaceholderHtml,
  renderUnboundHtml,
} from "./render";

describe("renderConfig", () => {
  it("renders an nginx server block with the supplied domain", () => {
    const c = renderConfig("example.com");
    expect(c).toContain("server_name example.com;");
    expect(c).toContain("root /var/www/example.com/public_html;");
    expect(c).toContain("listen 80;");
    expect(c).toContain("try_files $uri $uri/ =404;");
    expect(c).toContain("access_log /var/log/nginx/example.com.access.log;");
    expect(c).toContain("error_log /var/log/nginx/example.com.error.log;");
    expect(c).toMatch(/^# Generated by rinpanel for example\.com\n/);
    expect(c.endsWith("\n")).toBe(true);
  });

  it("substitutes a different domain consistently", () => {
    const c = renderConfig("foo.bar.co");
    expect(c).toContain("server_name foo.bar.co;");
    expect(c).toContain("root /var/www/foo.bar.co/public_html;");
    expect(c).not.toContain("example.com");
  });

  it("includes hardened security defaults", () => {
    const c = renderConfig("example.com");
    expect(c).toContain("server_tokens off;");
    expect(c).toContain('add_header X-Content-Type-Options "nosniff"');
    expect(c).toContain('add_header X-Frame-Options "SAMEORIGIN"');
    expect(c).toContain('add_header Referrer-Policy "strict-origin-when-cross-origin"');
    expect(c).toContain("add_header Permissions-Policy");
    expect(c).toContain("client_max_body_size 10m;");
  });

  it("blocks dotfiles and sensitive extensions", () => {
    const c = renderConfig("example.com");
    expect(c).toContain("location ~ /\\.");
    expect(c).toMatch(/location ~\* \\\.\(env\|log\|sql\|sqlite\|db\|bak\|backup\|swp\|swo\)\$/);
    // Both blocks should deny + 404
    const denyCount = (c.match(/deny all;/g) ?? []).length;
    const return404Count = (c.match(/return 404;/g) ?? []).length;
    expect(denyCount).toBeGreaterThanOrEqual(2);
    expect(return404Count).toBeGreaterThanOrEqual(2);
  });

  it("wires custom error pages with an internal location", () => {
    const c = renderConfig("example.com");
    expect(c).toContain("error_page 404 /_rinpanel/404.html;");
    expect(c).toContain("error_page 502 503 504 /_rinpanel/502.html;");
    expect(c).toMatch(/location \^~ \/_rinpanel\/ \{[^}]*internal;/);
  });
});

describe("renderPlaceholderHtml", () => {
  it("returns a PHOSPHOR-styled page containing the domain", () => {
    const h = renderPlaceholderHtml("example.com");
    expect(h.toLowerCase()).toContain("<!doctype html>");
    expect(h).toContain("example.com");
    expect(h).toContain("rinpanel");
    expect(h).toContain("domain");
  });
});

describe("renderError404Html", () => {
  it("returns themed 404 page", () => {
    const h = renderError404Html();
    expect(h.toLowerCase()).toContain("<!doctype html>");
    expect(h).toContain("404");
    expect(h.toLowerCase()).toContain("tidak ditemukan");
  });
});

describe("renderError502Html", () => {
  it("returns themed 502 page with amber accent", () => {
    const h = renderError502Html();
    expect(h.toLowerCase()).toContain("<!doctype html>");
    expect(h).toContain("502");
    expect(h.toLowerCase()).toContain("dijangkau");
    expect(h).toContain("#f59e0b");
  });
});

describe("renderUnboundHtml", () => {
  it("returns themed unbound page", () => {
    const h = renderUnboundHtml();
    expect(h.toLowerCase()).toContain("<!doctype html>");
    expect(h.toLowerCase()).toContain("belum terdaftar");
  });
});
