export function renderConfig(domain: string): string {
  return `# Generated by rinpanel for ${domain}
server {
    listen 80;
    server_name ${domain};
    root /var/www/${domain}/public_html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    access_log /var/log/nginx/${domain}.access.log;
    error_log /var/log/nginx/${domain}.error.log;
}
`;
}

export function renderPlaceholderHtml(domain: string): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${domain} · provisioned</title>
<meta name="viewport" content="width=device-width,initial-scale=1" />
<style>
  body { margin: 0; min-height: 100vh; display: grid; place-items: center;
         font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
         background: #0a0a0a; color: #e4e4e7; }
  .card { padding: 2rem 2.5rem; border: 1px solid rgba(255,255,255,0.09);
          border-radius: 0.75rem; background: rgba(20,22,26,0.7); }
  .eyebrow { color: #84cc16; font-size: 0.65rem; letter-spacing: 0.22em;
             text-transform: uppercase; }
  h1 { font-size: 1.5rem; margin: 0.6rem 0 0 0; }
  p { margin: 0.4rem 0 0 0; color: #71717a; font-size: 0.85rem; }
</style>
</head>
<body>
  <div class="card">
    <p class="eyebrow">▸ rinpanel · provisioned</p>
    <h1>${domain}</h1>
    <p>vhost is live. upload your site files via the file manager (coming soon).</p>
  </div>
</body>
</html>
`;
}
