import { describe, it, expect } from "vitest";
import { renderConfig, renderPlaceholderHtml } from "./render";

describe("renderConfig", () => {
  it("renders an nginx server block with the supplied domain", () => {
    const c = renderConfig("example.com");
    expect(c).toContain("server_name example.com;");
    expect(c).toContain("root /var/www/example.com/public_html;");
    expect(c).toContain("listen 80;");
    expect(c).toContain("try_files $uri $uri/ =404;");
    expect(c).toContain("access_log /var/log/nginx/example.com.access.log;");
    expect(c).toContain("error_log /var/log/nginx/example.com.error.log;");
    expect(c).toMatch(/^# Generated by rinpanel for example\.com\n/);
    expect(c.endsWith("\n")).toBe(true);
  });

  it("substitutes a different domain consistently", () => {
    const c = renderConfig("foo.bar.co");
    expect(c).toContain("server_name foo.bar.co;");
    expect(c).toContain("root /var/www/foo.bar.co/public_html;");
    expect(c).not.toContain("example.com");
  });
});

describe("renderPlaceholderHtml", () => {
  it("returns html containing the domain", () => {
    const h = renderPlaceholderHtml("example.com");
    expect(h.toLowerCase()).toContain("<!doctype html>");
    expect(h).toContain("example.com");
    expect(h.toUpperCase()).toContain("PROVISIONED");
  });
});
